// Generated by tools/make-puzzles.js. Do not edit by hand.
// Boards use R Y G B P for red, yellow, green, blue, purple and . for empty.
// Solutions list the tapped cells as row+column digits.
(function (root) {
  'use strict';
  const PACK = [
    // #1: 12 tiles, 2-move solution, random play clears 100%, 2/2 opening moves solvable
    { board: ["P.....","P.....","GP....","P.....","P..B..",".BBYBB"], solution: '53 20' },
    // #2: 12 tiles, 2-move solution, random play clears 100%, 2/2 opening moves solvable
    { board: [".....Y",".....Y","....YB",".....Y","...P.Y",".PPYPP"], solution: '25 53' },
    // #3: 12 tiles, 3-move solution, random play clears 100%, 3/3 opening moves solvable
    { board: ["......","...P..","Y..P.P","Y.....","GY....","YPPGP."], solution: '23 53 40' },
    // #4: 12 tiles, 2-move solution, random play clears 50%, 2/4 opening moves solvable
    { board: [".....P",".....P","....RB","....PP","...P..",".PPYPP"], solution: '35 53' },
    // #5: 12 tiles, 3-move solution, random play clears 49%, 2/3 opening moves solvable
    { board: ["...BBR",".....B","......","Y.....","Y.G...","GYYGG."], solution: '05 52 50' },
    // #6: 18 tiles, 4-move solution, random play clears 14%, 2/3 opening moves solvable
    { board: ["P.....","P...PP","R...BB","P..BYP","P..YPY","...YYB"], solution: '20 54 54 45' },
    // #7: 18 tiles, 4-move solution, random play clears 13%, 2/6 opening moves solvable
    { board: [".....B",".....B","GY...R","PYPP.B","BGYY..","PGPP.."], solution: '30 41 51 25' },
    // #8: 18 tiles, 4-move solution, random play clears 4%, 1/4 opening moves solvable
    { board: ["R.....","R....R","GGRP.P","GR...P","RRP...","GYPP.."], solution: '25 40 20 51' },
    // #9: 18 tiles, 4-move solution, random play clears 0%, 1/8 opening moves solvable
    { board: ["......","......","PP.B..","G.BYBB","P.YBYY","P.YYBY"], solution: '20 33 43 54' },
    // #10: 18 tiles, 4-move solution, random play clears 0%, 1/8 opening moves solvable
    { board: ["RGGRG.","GGRG..","RRGRG.","GR.G..","G.....","......"], solution: '23 03 20 10' },
    // #11: 24 tiles, 5-move solution, random play clears 3%, 3/10 opening moves solvable
    { board: ["RRGRR.","RGGR..","GGRGP.","RR..P.","GR...P","G..PPG"], solution: '54 02 03 20 10' },
    // #12: 24 tiles, 5-move solution, random play clears 3%, 1/9 opening moves solvable
    { board: ["..PBPR","PPGPPR","....RB","PG...R","PGGP.R","RYG..P"], solution: '25 40 42 03 12' },
    // #13: 24 tiles, 5-move solution, random play clears 3%, 2/10 opening moves solvable
    { board: ["......",".YPYP.",".PYBY.",".GGYGY",".YYGYP","GYYGYY"], solution: '44 41 53 52 43' },
    // #14: 24 tiles, 5-move solution, random play clears 1%, 2/8 opening moves solvable
    { board: ["G.PG..","GPY..P","PYYP.P","GY..RR","YP..PP","YYPP.."], solution: '45 11 21 30 51' },
    // #15: 24 tiles, 5-move solution, random play clears 1%, 1/7 opening moves solvable
    { board: ["PGRRP.","GPGR..","GGPGR.","PGRR..","GPRP..",".R.P.."], solution: '23 10 40 20 01' },
    // #16: 24 tiles, 5-move solution, random play clears 1%, 1/14 opening moves solvable
    { board: ["GP....","RPG..P","GRG..P","GGPG.Y","PGGP.P","PPG..P"], solution: '35 31 10 41 20' },
    // #17: 24 tiles, 5-move solution, random play clears 0%, 2/7 opening moves solvable
    { board: ["BBRRBR",".RRBRB","B..RRB",".PPBBR","...RBR",".P...."], solution: '31 03 02 15 25' },
    // #18: 24 tiles, 5-move solution, random play clears 0%, 2/9 opening moves solvable
    { board: ["......","GY...P","GYY..P","YGYP.Y","GYPYYP","YPYYPP"], solution: '35 52 53 30 40' },
    // #19: 24 tiles, 5-move solution, random play clears 0%, 1/8 opening moves solvable
    { board: ["GGRGG.","PRGG.P","GRR..P","GPGR.Y","PPG..P",".....P"], solution: '35 22 30 02 10' },
    // #20: 24 tiles, 5-move solution, random play clears 0%, 1/12 opening moves solvable
    { board: ["G..PPR","YG...P","GYGG..","GGYY..","YGGY..","GYYGY."], solution: '05 50 20 30 51' },
    // #21: 30 tiles, 6-move solution, random play clears 1%, 1/5 opening moves solvable
    { board: ["PP..RB","GY..RR","PBBRBB","PGGBRB","GGYGPG","PYPP.."], solution: '00 42 51 50 25 15' },
    // #22: 30 tiles, 6-move solution, random play clears 0%, 7/15 opening moves solvable
    { board: ["P..P..","PGPGPP","GGPG..","GPGYPY","YGYYPY","PGYGYP"], solution: '33 43 30 52 30 51' },
    // #23: 30 tiles, 7-move solution, random play clears 0%, 1/8 opening moves solvable
    { board: [".PPRP.","YYGYPG","GYGYY.","YGPG..","YYGGY.","GGYYPP"], solution: '04 23 42 22 30 50 51' },
    // #24: 30 tiles, 6-move solution, random play clears 0%, 2/11 opening moves solvable
    { board: ["PPGPBP","..YP.P",".BBYPB",".PBYBP",".YYBPY","PPYBYP"], solution: '03 33 34 25 54 53' },
    // #25: 30 tiles, 6-move solution, random play clears 0%, 2/12 opening moves solvable
    { board: ["RRBBRR","PPBRPG","RBRBBP",".RRPBP","PPBPPB","..P..."], solution: '22 24 33 25 13 03' },
    // #26: 30 tiles, 6-move solution, random play clears 0%, 2/14 opening moves solvable
    { board: ["GPGRPP","GRRBRG","RPGRRP","GGRGG.","GPGPG.",".P.P.."], solution: '03 12 22 03 21 20' },
    // #27: 30 tiles, 7-move solution, random play clears 0%, 1/10 opening moves solvable
    { board: [".PYP.B",".PBYPB","..BBYY","BBYBBY","YBBYYB",".YYBYY"], solution: '11 13 23 32 42 35 53' },
    // #28: 30 tiles, 7-move solution, random play clears 0%, 1/11 opening moves solvable
    { board: ["..P..P","GPGGPP","GPGYGR","PYPG.P","GPYPYP","GPYGY."], solution: '25 41 43 32 21 40 51' },
    // #29: 30 tiles, 7-move solution, random play clears 0%, 1/14 opening moves solvable
    { board: ["PPGB..","GYRRP.","GGYGYY","RGGPP.","GRPGGP","..PBPP"], solution: '23 33 53 20 30 30 00' },
    // #30: 30 tiles, 6-move solution, random play clears 0%, 1/14 opening moves solvable
    { board: ["RBRRBB","PBRBRB","PRBBPR","YPBRBB","P..PBB","P....P"], solution: '30 25 35 45 03 04' },
    // #31: 36 tiles, 9-move solution, random play clears 0%, 5/19 opening moves solvable
    { board: ["BBPBPB","PPBYBY","YPYPBP","PYBBPP","PYPYBB","YBYBYY"], solution: '20 31 05 53 24 25 22 53 42' },
    // #32: 36 tiles, 9-move solution, random play clears 0%, 3/12 opening moves solvable
    { board: ["PGPPGG","YPYPPG","YGGBYY","GYYGYG","GGYYPG","YPGGYP"], solution: '14 03 54 21 40 50 31 30 51' },
    // #33: 36 tiles, 8-move solution, random play clears 0%, 3/13 opening moves solvable
    { board: ["PPBPPG","PYYGGP","YYBYYB","PRPYGP","PPYRPY","YYPPYY"], solution: '02 55 20 42 42 55 51 52' },
    // #34: 36 tiles, 9-move solution, random play clears 0%, 4/18 opening moves solvable
    { board: ["BRBRRB","PBRBRR","RRBRBR","PBRPPB","PBRPRR","RRBRRB"], solution: '43 20 21 05 02 05 03 14 05' },
    // #35: 36 tiles, 8-move solution, random play clears 0%, 4/18 opening moves solvable
    { board: ["PRBRBR","RPRBPP","BRBBRR","YBRRBR","BPPBPP","BPPBPP"], solution: '30 53 43 34 12 23 13 04' },
    // #36: 36 tiles, 9-move solution, random play clears 0%, 3/17 opening moves solvable
    { board: ["GRRPPG","PGRGGR","GGPPGG","GPGGPB","RGGPPB","BBYBBY"], solution: '00 55 31 55 22 30 00 20 01' },
    // #37: 36 tiles, 8-move solution, random play clears 0%, 3/21 opening moves solvable
    { board: ["GRRGRR","RGRGGR","RRGBGP","GGYGPG","PGGRGG","GRRGRR"], solution: '53 33 10 20 00 12 02 02' },
    // #38: 36 tiles, 9-move solution, random play clears 0%, 2/14 opening moves solvable
    { board: ["PPYPGP","GYGGYY","PYPYPG","YGYPYG","GGYPYY","GYGYGP"], solution: '22 11 21 44 41 41 41 40 30' },
    // #39: 36 tiles, 8-move solution, random play clears 0%, 3/21 opening moves solvable
    { board: ["BRRBRR","BRBRBB","YBRRBB","BRBPGP","BBPBBP","PGPPBB"], solution: '20 51 11 25 45 35 14 03' },
    // #40: 36 tiles, 8-move solution, random play clears 0%, 2/14 opening moves solvable
    { board: ["RGGRRP","RGRGRP","GPGGPY","GGRPGP","PRPRGP","GPGRPG"], solution: '25 50 32 23 20 30 12 01' },
    // #41: 36 tiles, 8-move solution, random play clears 0%, 2/16 opening moves solvable
    { board: ["BRRPBB","RRBRBB","BBRBRR","RBRBRR","BPBPBB","RRBRPB"], solution: '52 42 33 25 03 02 14 25' },
    // #42: 36 tiles, 9-move solution, random play clears 0%, 1/11 opening moves solvable
    { board: ["RRPRRB","PRPRRB","GBRBBR","PGGRPB","YRYPRP","PRGBRP"], solution: '43 45 40 30 21 15 03 04 05' },
    // #43: 36 tiles, 8-move solution, random play clears 0%, 2/22 opening moves solvable
    { board: ["RBRBBP","BRRBRR","RRBGBB","RBRRBB","BRBPRR","RBRPBB"], solution: '00 44 32 13 13 02 35 25' },
    // #44: 36 tiles, 9-move solution, random play clears 0%, 1/12 opening moves solvable
    { board: ["RPGGRR","GRGGRP","GGPRPP","RGRPGG","GRGGRP","RPGGPP"], solution: '31 32 52 33 03 34 03 30 20' },
    // #45: 36 tiles, 9-move solution, random play clears 0%, 1/12 opening moves solvable
    { board: ["RGGPGG","GPRRPP","GRGGPG","RGRRGY","RRGPPG","GPRPPG"], solution: '14 35 32 00 44 01 33 01 11' },
    // #46: 36 tiles, 9-move solution, random play clears 0%, 1/14 opening moves solvable
    { board: ["BGYBPB","BPPGYP","PGGYGP","YYGPGY","GYYGYY","GGYPYP"], solution: '11 05 54 32 30 21 50 52 52' },
    // #47: 36 tiles, 9-move solution, random play clears 0%, 1/16 opening moves solvable
    { board: ["GGRRGP","PRGGRG","GPRRPG","GRGGRP","RPRRGR","GRPPBP"], solution: '40 54 13 43 32 01 13 30 02' },
    // #48: 36 tiles, 9-move solution, random play clears 0%, 1/18 opening moves solvable
    { board: ["PBPPGP","PBYPYB","YYBYYB","PYBYBY","YPYBPB","PYYPBP"], solution: '04 20 52 43 45 44 52 35 44' },
    // #49: 36 tiles, 9-move solution, random play clears 0%, 1/20 opening moves solvable
    { board: ["PYRBBR","PBGBBR","YPPYRB","YPYRBR","BYPPBR","YYGYPP"], solution: '31 31 52 42 34 34 52 24 25' },
    // #50: 36 tiles, 8-move solution, random play clears 0%, 1/23 opening moves solvable
    { board: ["RRBRRB","PRRBRR","PGRRBR","RRPBRB","PPRRBP","PPYPBP"], solution: '30 51 01 34 35 02 04 15' },
  ];
  if (typeof module !== 'undefined' && module.exports) module.exports = PACK;
  else root.SHIFT_PUZZLE_PACK = PACK;
})(typeof window !== 'undefined' ? window : globalThis);
