// Builds the numbered puzzle pack (puzzle-pack.js) for puzzle mode.
//
//   node tools/make-puzzles.js
//
// Puzzles get bigger through the pack, and within each size they are ordered
// from easiest to hardest. Difficulty is how often random play clears the
// puzzle, then how few of the opening moves still lead to a solution.
const fs = require('node:fs');
const path = require('node:path');
const { mulberry32 } = require('../logic.js');
const P = require('../puzzles.js');

// [tiles, how many puzzles]
const TIERS = [
  [12, 5],
  [18, 5],
  [24, 10],
  [30, 10],
  [36, 20],
];
const PLAYOUTS = 300;
const LETTERS = 'RYGBP';

function rate(board, rng) {
  let wins = 0;
  for (let i = 0; i < PLAYOUTS; i++) {
    let g = board;
    for (;;) {
      const moves = P.legalMoves(g);
      if (!moves.length) break;
      g = P.play(g, ...moves[Math.floor(rng() * moves.length)]);
    }
    if (P.count(g) === 0) wins++;
  }
  const first = P.legalMoves(board);
  const good = first.filter((m) => P.solve(P.play(board, ...m), 100000)).length;
  return { randomWins: wins / PLAYOUTS, goodFirstMoves: good, firstMoves: first.length };
}

const pack = [];
let seed = 1;
for (const [tiles, n] of TIERS) {
  const tier = [];
  const seen = new Set();
  while (tier.length < n) {
    const rng = mulberry32(seed++);
    const built = P.generate({ tiles, rng });
    if (!built || seen.has(P.key(built.board))) continue;
    seen.add(P.key(built.board));
    // Double-check: the recorded solution really clears the board.
    let g = built.board;
    for (const m of built.solution) g = P.play(g, ...m);
    if (!g || P.count(g) !== 0) throw new Error(`seed ${seed - 1}: solution does not clear the board`);
    tier.push({ board: built.board, solution: built.solution, ...rate(built.board, rng) });
    process.stderr.write(`${tiles} tiles: ${tier.length}/${n}\r`);
  }
  tier.sort((a, b) => b.randomWins - a.randomWins || b.goodFirstMoves / b.firstMoves - a.goodFirstMoves / a.firstMoves);
  pack.push(...tier);
}

const lines = pack.map((p, i) => {
  const board = p.board.map((row) => row.map((v) => (v < 0 ? '.' : LETTERS[v])).join(''));
  const solution = p.solution.map(([r, c]) => `${r}${c}`).join(' ');
  return (
    `    // #${i + 1}: ${P.count(p.board)} tiles, ${p.solution.length}-move solution, ` +
    `random play clears ${(p.randomWins * 100).toFixed(0)}%, ${p.goodFirstMoves}/${p.firstMoves} opening moves solvable\n` +
    `    { board: ${JSON.stringify(board)}, solution: '${solution}' },`
  );
});

const out = `// Generated by tools/make-puzzles.js. Do not edit by hand.
// Boards use R Y G B P for red, yellow, green, blue, purple and . for empty.
// Solutions list the tapped cells as row+column digits.
(function (root) {
  'use strict';
  const PACK = [
${lines.join('\n')}
  ];
  if (typeof module !== 'undefined' && module.exports) module.exports = PACK;
  else root.SHIFT_PUZZLE_PACK = PACK;
})(typeof window !== 'undefined' ? window : globalThis);
`;
fs.writeFileSync(path.join(__dirname, '..', 'puzzle-pack.js'), out);
console.log(`\nWrote ${pack.length} puzzles.`);
